# Usamos Nginx ligero
FROM nginx:alpine

# Borramos la página por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiamos nuestro index.html a la carpeta pública de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Nginx expone el puerto 80 por defecto
EXPOSE 80

# No necesitamos CMD, Nginx arranca solo