name: Deploy Multi-Account Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply Multi-Account"
    runs-on: ubuntu-latest

    # AQUÍ ESTÁ LA CLAVE: Mapeamos los Secretos a Variables de Terraform
    env:
      # Credenciales Cuenta 1 (Backend) -> Mapean a var.creds_backend_...
      TF_VAR_creds_backend_access: ${{ secrets.BACKEND_ACCESS_KEY }}
      TF_VAR_creds_backend_secret: ${{ secrets.BACKEND_SECRET_KEY }}
      TF_VAR_creds_backend_token: ${{ secrets.BACKEND_SESSION_TOKEN }}

      # Credenciales Cuenta 2 (Frontend) -> Mapean a var.creds_frontend_...
      TF_VAR_creds_frontend_access: ${{ secrets.FRONTEND_ACCESS_KEY }}
      TF_VAR_creds_frontend_secret: ${{ secrets.FRONTEND_SECRET_KEY }}
      TF_VAR_creds_frontend_token: ${{ secrets.FRONTEND_SESSION_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # Truco para forzar que redescargue el código si cambiaste algo en la App
      # (Solo necesario si tus instancias no son Auto Scaling Groups)
      - name: Taint instances to force update
        continue-on-error: true
        run: |
          terraform taint aws_instance.servidor_backend || true
          terraform taint aws_instance.servidor_frontend || true

      - name: Terraform Apply
        run: terraform apply -auto-approve
